### ISSUE TITLE
Updating a Gemfile crashes

### ISSUE THREAD

**Issue by markets** [Shpigford/gemfile.directory#18]
hey @Shpigford 👋🏼 very interesting initiative!

I'm trying to update a Gemfile I submitted some weeks ago (🏆 Open Source Hereos https://gemfile.directory/gemfiles/2803a936-8b2e-48fe-9d94-305482e0291c), but when I click the "Update Gemfile" button I got the following error:

<img width="576" alt="Captura de pantalla 2024-01-17 a las 16 43 06" src="https://github.com/Shpigford/gemfile.directory/assets/576701/a5aa43f9-f341-4634-96be-42548e80ab4b">

(no other attributes were changed, only copy-pasted new Gemfile)

**Comment by robzolkos** [comment]
@Shpigford trying to write a failing test for this and well...failing.  cos it works.  and also works in development.  But is definitely broken in production.   Do you get error logs?  If so I just encountered a 500 doing this in production at 7.32pm  EST Feb 8.  If you can paste in anything relevant I can hunt this down further.

**Comment by markets** [comment]
Thanks for taking a look @robzolkos 👍🏼  

I didn't tried locally, but taking a quick look, I've found a couple of _weird_ lines here:

https://github.com/Shpigford/gemfile.directory/blob/f76e031d33cb536c51551da97463756465552ba3/app/controllers/gemfiles_controller.rb#L42-L43

It performs a second `save` after the actual `update`. This shouldn't be the reason of the crash, but anyway I think the second `save` should be ✂️.

**Comment by Shpigford** [comment]
Here's the error. Need to figure out what to do to fix it. 🙃

```
I, [2024-02-10T20:13:23.773359 #608495]  INFO -- : [a2ca86f6-302a-4dfa-a408-5d69cc26e18d] Completed 500 Internal Server Error in 253ms (ActiveRecord: 224.7ms | Allocations: 6235)
E, [2024-02-10T20:13:23.774992 #608495] ERROR -- : [a2ca86f6-302a-4dfa-a408-5d69cc26e18d]
[a2ca86f6-302a-4dfa-a408-5d69cc26e18d] RedisClient::CommandError (NOAUTH Authentication required.):
[a2ca86f6-302a-4dfa-a408-5d69cc26e18d]
[a2ca86f6-302a-4dfa-a408-5d69cc26e18d] app/models/gemfile.rb:46:in `block in parse_content'
[a2ca86f6-302a-4dfa-a408-5d69cc26e18d] app/models/gemfile.rb:31:in `each'
[a2ca86f6-302a-4dfa-a408-5d69cc26e18d] app/models/gemfile.rb:31:in `parse_content'
[a2ca86f6-302a-4dfa-a408-5d69cc26e18d] app/controllers/gemfiles_controller.rb:40:in `update'
```

**Comment by Shpigford** [comment]
Well that was easy. Literally just had to click a single button in Hatchbox. 🪄

Should be good to go now!

@markets Feel free to submit a PR for that duplicate save. 🙌
