### ISSUE TITLE
There is an XSS by passing user controlled data to link_to

### ISSUE THREAD

**Issue by gregmolnar** [Shpigford/gemfile.directory#5]
If someone sets the site URL to a javascript payload, it can lead to an XSS: https://gemfile.directory/gemfiles/7c560616-ac8f-4cb7-8428-22b4ab7a29e4

**Comment by Shpigford** [comment]
@gregmolnar Given it's using Rails link_to, should that escape Javascript?

```
<%= link_to '<i class="text-xl text-white fa-solid fa-link hover:text-amber-300"></i>'.html_safe, @gemfile.app_link %>
```

**Comment by gregmolnar** [comment]
It doesn't escape javascript by design. The second parameter is a URL string and that has a scheme, which can  be javascript and that causes the problem here. You can see on the example link above. Open your browser's console and it will output a message there. 
You should add validation to that attribute and only permit http/https as a URL scheme.
